// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6gsUa6ur7xpdzCKtpjaacA9ADAS6X2hs',
    appId: '1:253689258332:web:272b8026cd94ded6482199',
    messagingSenderId: '253689258332',
    projectId: 'fleet-maintenance-app-f64aa',
    authDomain: 'fleet-maintenance-app-f64aa.firebaseapp.com',
    storageBucket: 'fleet-maintenance-app-f64aa.firebasestorage.app',
    measurementId: 'G-RE1LRWPTMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf3OQuO4WTrURAdWIGWYAMlmcis4HPa78',
    appId: '1:253689258332:android:3460766d73f524dd482199',
    messagingSenderId: '253689258332',
    projectId: 'fleet-maintenance-app-f64aa',
    storageBucket: 'fleet-maintenance-app-f64aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoxq1k0j6C626B9Z0lcDOwjRlxr9EGq3U',
    appId: '1:253689258332:ios:cc84821a153a5649482199',
    messagingSenderId: '253689258332',
    projectId: 'fleet-maintenance-app-f64aa',
    storageBucket: 'fleet-maintenance-app-f64aa.firebasestorage.app',
    iosBundleId: 'com.example.fleetMaintenanceApp',
  );
}
